name: seller_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  fluid_bottom_nav_bar:
  fancy_bottom_navigation_2:
  intl:
  shared_preferences:
  fluttertoast:
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/signal_1.png
    - assets/images/smartphone_call_11.png
    - assets/images/view_12.png
    - assets/images/half_battery_1.png
    - assets/images/wifi_11.png
    - assets/images/mail_1.png
    - assets/images/user_32.png
    - assets/images/half_battery_1.png
    - assets/images/view_12.png
    - assets/images/arrow_down_sign_to_navigate_21.png
    - assets/images/signal_1.png
    - assets/images/mail_1.png
    - assets/images/wifi_11.png
    - assets/images/view_12.png
    - assets/images/wifi_11.png
    - assets/images/signal_1.png
    - assets/images/half_battery_1.png
    - assets/images/wifi_11.png
    - assets/images/smartphone_call_11.png
    - assets/images/touch_1.png
    - assets/images/half_battery_1.png
    - assets/images/signal_1.png
    - assets/images/wifi_11.png
    - assets/images/view_12.png
    - assets/images/signal_1.png
    - assets/images/smartphone_call_11.png
    - assets/images/half_battery_1.png
    - assets/images/onion_png_992131.png
    - assets/images/home_11.png
    - assets/images/istockphoto_1089759056612_x_6121.jpeg
    - assets/images/loupe_1.png
    - assets/images/purepng_1.png
    - assets/images/lady_finger_okra_png_hd_image_1.png
    - assets/images/tomato_png_image_1.png
    - assets/images/image.jpeg
    - assets/images/cauliflower_transparent_image_thumb_1.png
    - assets/images/half_battery_1.png
    - assets/images/gettyimages_153946385_ca_1_ccfaad_9_be_44325_afc_434_b_305_adc_0_d_1.png
    - assets/images/user_32.png
    - assets/images/brinjal_bunch_free_download_png_hq_1.png
    - assets/images/signal_1.png
    - assets/images/wifi_11.png
    - assets/images/notification_1.png
    - assets/images/dots_31.png
    - assets/images/arrow_down_sign_to_navigate_16.png
    - assets/images/milk_png_free_download_711.png
    - assets/images/menu_21.png
    - assets/images/location_51.png
    - assets/images/drendering_vanilla_ice_cream_on_transparent_background_png_1.png
    - assets/images/location_51.png
    - assets/images/wifi_11.png
    - assets/images/home_11.png
    - assets/images/dots_31.png
    - assets/images/signal_1.png
    - assets/images/loupe_1.png
    - assets/images/orange_png_7772.png
    - assets/images/watermelon_png_free_download_1800_x_18001.png
    - assets/images/ice_cream_png_404271.png
    - assets/images/pngimg_1.png
    - assets/images/istockphoto_1089759056612_x_6121.jpeg
    - assets/images/c_4_d_9_eefa_0_d_4136938_ed_03_c_7359286_f_7_a_1.png
    - assets/images/cauliflower_transparent_image_thumb_1.png
    - assets/images/tomato_png_image_1.png
    - assets/images/sort_2.png
    - assets/images/milk_png_free_download_711.png
    - assets/images/bunch_of_grapes_on_transparent_background_png_1.png
    - assets/images/onion_png_992131.png
    - assets/images/brinjal_bunch_free_download_png_hq_1.png
    - assets/images/purepng_1.png
    - assets/images/filter_1.png
    - assets/images/frosty_boy_soft_serve_ice_cream_01.png
    - assets/images/notification_1.png
    - assets/images/lady_finger_okra_png_hd_image_1.png
    - assets/images/menu_21.png
    - assets/images/half_battery_1.png
    - assets/images/user_32.png
    - assets/images/half_battery_1.png
    - assets/images/otp_1.png
    - assets/images/wifi_11.png
    - assets/images/signal_1.png
    - assets/images/signal_1.png
    - assets/images/brinjal_bunch_free_download_png_hq_1.png
    - assets/images/lady_finger_okra_png_hd_image_1.png
    - assets/images/sort_2.png
    - assets/images/notification_1.png
    - assets/images/onion_png_992131.png
    - assets/images/tomato_png_image_1.png
    - assets/images/wifi_11.png
    - assets/images/back_21.png
    - assets/images/user_32.png
    - assets/images/dots_31.png
    - assets/images/pin_11.png
    - assets/images/pngimg_3.png
    - assets/images/filter_1.png
    - assets/images/half_battery_1.png
    - assets/images/home_11.png
    - assets/images/loupe_1.png
    - assets/images/cauliflower_transparent_image_thumb_1.png
    - assets/images/location_51.png
    - assets/images/wifi_11.png
    - assets/images/loupe_1.png
    - assets/images/location_83.png
    - assets/images/notification_1.png
    - assets/images/user_32.png
    - assets/images/delivery_bike_1.png
    - assets/images/phone_call_42.png
    - assets/images/location_51.png
    - assets/images/signal_1.png
    - assets/images/home_11.png
    - assets/images/man_1.png
    - assets/images/half_battery_1.png
    - assets/images/image_1.png
    - assets/vectors/ellipse_201_x2.svg
    - assets/images/location_51.png
    - assets/images/notification_1.png
    - assets/images/star_24.png
    - assets/images/chat_1.png
    - assets/images/man_1.png
    - assets/images/wifi_11.png
    - assets/images/signal_1.png
    - assets/images/half_battery_1.png
    - assets/images/message_1.png
    - assets/images/loupe_1.png
    - assets/images/phone_call_42.png
    - assets/images/location_71.png
    - assets/images/user_32.png
    - assets/images/phone_21.png
    - assets/images/home_11.png
    - assets/images/star_31.png
    - assets/images/half_battery_1.png
    - assets/images/wifi_11.png
    - assets/images/smartphone_call_11.png
    - assets/images/signal_1.png
    - assets/images/wifi_11.png
    - assets/images/half_battery_1.png
    - assets/images/signal_1.png
    - assets/images/view_12.png
    - assets/images/smartphone_call_11.png
    - assets/images/half_battery_1.png
    - assets/images/view_12.png
    - assets/images/signal_1.png
    - assets/images/wifi_11.png
    - assets/images/signal_1.png
    - assets/images/half_battery_1.png
    - assets/images/smartphone_call_11.png
    - assets/images/wifi_11.png
    - assets/images/wifi_11.png
    - assets/images/half_battery_1.png
    - assets/images/touch_1.png
    - assets/images/smartphone_call_11.png
    - assets/images/signal_1.png
    - assets/images/wifi_11.png
    - assets/images/otp_1.png
    - assets/images/half_battery_1.png
    - assets/images/signal_1.png
    - assets/images/back_21.png
    - assets/images/dots_31.png
    - assets/images/loupe_1.png
    - assets/images/home_11.png
    - assets/images/shop_1.png
    - assets/images/notification_1.png
    - assets/images/flats_1.png
    - assets/images/location_51.png
    - assets/images/half_battery_1.png
    - assets/images/landmark_1.png
    - assets/images/wifi_11.png
    - assets/images/user_32.png
    - assets/images/signal_1.png
    - assets/images/delivery_bike_1.png
    - assets/images/user_32.png
    - assets/images/signal_1.png
    - assets/images/image_1.png
    - assets/images/half_battery_1.png
    - assets/images/notification_1.png
    - assets/images/motorcycle_1.png
    - assets/images/walking_1.png
    - assets/images/location_51.png
    - assets/images/loupe_1.png
    - assets/images/bicycle_11.png
    - assets/images/van_1.png
    - assets/images/wifi_11.png
    - assets/images/location_83.png
    - assets/images/home_11.png
    - assets/vectors/ellipse_20_x2.svg
    - assets/images/right-arrow-icon-removebg-preview.png
    - assets/images/leftarrow-removebg-preview.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
